/**
 * 将 3D LUT 数据输出为 Adobe .CUBE 格式字符串。
 * @param {Float64Array} lut - LUT 数据，3 * size³ 个值，RGB 逐像素，范围 [0, 1]
 * @param {number} size - LUT 网格尺寸
 * @returns {string} - .CUBE 格式文本
 */
export function lutToCubeString(lut, size = 33) {
  const lines = [];
  lines.push('# Generated by Color Muse');
  lines.push('TITLE "ColorMuse_' + size + 'x' + size + 'x' + size + '"');
  lines.push('LUT_3D_SIZE ' + size);
  lines.push('');

  for (let i = 0; i < lut.length; i += 3) {
    const r = lut[i].toFixed(6);
    const g = lut[i + 1].toFixed(6);
    const b = lut[i + 2].toFixed(6);
    lines.push(r + ' ' + g + ' ' + b);
  }

  return lines.join('\n');
}

/**
 * 触发浏览器下载 .CUBE 文件。
 * @param {Float64Array} lut - LUT 数据
 * @param {number} size - LUT 网格尺寸
 * @param {string} filename - 下载文件名
 */
export function downloadLutAsCube(lut, size = 33, filename = 'color-muse-lut.cube') {
  const content = lutToCubeString(lut, size);
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
